# Generated by Django 4.2.15 on 2025-06-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_project_version_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosubmitquestions',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
