# Generated by Django 4.2.15 on 2025-06-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_add_created_at_to_perspective_answer"),
        ("projects", "0016_tosubmitquestions_percentage"),
    ]

    operations = []
