# Generated by Django 4.2.15 on 2025-06-24 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_merge_20250624_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspectiveanswer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
