# Generated by Django 4.2.15 on 2025-07-08 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0011_comment_project_version"),
        ("label_types", "0007_delete_relationtypeold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0018_add_project_version_to_annotations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("example", "user", "label", "project_version")},
        ),
        migrations.AlterUniqueTogether(
            name="textlabel",
            unique_together={("example", "user", "text", "project_version")},
        ),
    ]
