# Generated by Django 4.2.15 on 2025-06-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0010_alter_comment_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="project_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
