<template>
  <v-card>
    <v-card-title>
      <v-row align="center">
        <v-col cols="12" sm="6">
          <v-text-field
            v-model="search"
            label="Search"
            prepend-icon="mdi-magnify"
            single-line
            hide-details
          ></v-text-field>
          <!-- Bloco abaixo do search para definir o threshold -->
          <v-text-field
            v-model.number="thresholdPercentage"
            label="Threshold Percentage"
            type="number"
            prepend-icon="mdi-percent"
            single-line
            hide-details
            hint="Percentage ≥ threshold = Agreement, < threshold = Disagreement"
            persistent-hint
          ></v-text-field>
        </v-col>
        <v-col cols="12" sm="6" class="text-right">
          <v-btn-toggle
            v-model="sortOrder"
            mandatory
            @change="updateSort"
          >
            <v-btn small value="desc">
              <v-icon>mdi-sort-descending</v-icon>
              Descending
            </v-btn>
            <v-btn small value="asc">
              <v-icon>mdi-sort-ascending</v-icon>
              Ascending
            </v-btn>
          </v-btn-toggle>
          <!-- Botão Gerar Automaticamente -->
          <v-btn color="primary" class="ml-2" @click="autoGenerateDiscrepancies">
            Generate
          </v-btn>
        </v-col>
      </v-row>

      <!-- Perspective Filters -->
      <v-row class="mt-2">
        <v-col cols="12" md="10" lg="8" class="ml-auto">
          <v-btn
            color="primary"
            class="filter-btn"
            @click="showFilterDialog = true"
          >
            <v-icon left>mdi-filter-variant</v-icon>
            Perspective Filters
            <v-chip
              v-if="hasActiveFilters"
              color="error"
              small
              class="ml-2"
            >
              {{ activeFiltersCount }}
            </v-chip>
          </v-btn>
        </v-col>
      </v-row>
    </v-card-title>

    <!-- Filter Dialog -->
    <v-dialog
      v-model="showFilterDialog"
      max-width="900px"
      content-class="filter-dialog"
    >
      <v-card class="filter-dialog-card">
        <v-card-title class="filter-dialog-title">
          <div class="d-flex align-center">
            <v-icon left color="primary" class="mr-2">mdi-filter-variant</v-icon>
            <span class="text-h6">Perspective Filters</span>
          </div>
          <v-spacer></v-spacer>
          <v-btn
            v-if="hasActiveFilters"
            color="error"
            text
            class="clear-filters-btn"
            @click="clearFilters"
          >
            <v-icon small left>mdi-close</v-icon>
            Clear Filters
          </v-btn>
          <v-btn
            icon
            @click="showFilterDialog = false"
          >
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </v-card-title>

        <v-card-text class="filter-dialog-content">
          <v-row>
            <v-col v-for="(group, groupIndex) in perspectiveGroups" 
              :key="groupIndex" 
              cols="12" 
              md="6"
            >
              <v-card flat class="perspective-filter-card">
                <v-card-title class="py-2">
                  <v-icon left color="primary" class="mr-2">mdi-account-group</v-icon>
                  <span class="text-subtitle-1 font-weight-medium">{{ group.name }}</span>
                </v-card-title>
                <v-divider class="mx-4"></v-divider>
                <v-card-text class="py-2">
                  <div v-for="question in group.questions" :key="question.id" class="mb-4">
                    <div class="d-flex align-center mb-1">
                      <v-icon small color="primary" class="mr-2">mdi-help-circle</v-icon>
                      <div class="text-subtitle-2 font-weight-medium">{{ question.question }}</div>
                    </div>
                    
                    <!-- String Options -->
                    <v-select
                      v-if="question.data_type === 'string' && 
                      question.options && question.options.length > 0"
                      v-model="selectedAnswers[question.id]"
                      :items="question.options"
                      :label="'Select ' + question.question"
                      multiple
                      chips
                      deletable-chips
                      clearable
                      outlined
                      dense
                      class="mt-1"
                      @change="applyFilters"
                    >
                      <template #selection="{ item, index }">
                        <v-chip
                          v-if="index < 2"
                          color="primary"
                          outlined
                          x-small
                          class="mr-1"
                        >
                          {{ item }}
                        </v-chip>
                        <span
                          v-else-if="index === 2"
                          class="grey--text text-caption pl-2"
                        >
                          (+{{ selectedAnswers[question.id].length - 2 }} others)
                        </span>
                      </template>
                    </v-select>

                    <!-- Integer Options (free numeric input) -->
                    <v-text-field
                      v-else-if="question.data_type === 'int'"
                      v-model="selectedAnswers[question.id]"
                      :label="'Filter by ' + question.question"
                      type="number"
                      clearable
                      outlined
                      dense
                      class="mt-1"
                      placeholder="Enter a number"
                      @input="applyFilters"
                    />

                    <!-- Boolean Options -->
                    <v-radio-group
                      v-else-if="question.data_type === 'boolean'"
                      v-model="selectedAnswers[question.id]"
                      row
                      dense
                      class="mt-1"
                      @change="applyFilters"
                    >
                      <v-radio
                        :value="true"
                        color="primary"
                        class="mr-4"
                      >
                        <template #label>
                          <div class="d-flex align-center">
                            <v-icon small color="success" class="mr-1">mdi-check-circle</v-icon>
                            <span class="text-caption">Yes</span>
                          </div>
                        </template>
                      </v-radio>
                      <v-radio
                        :value="false"
                        color="primary"
                      >
                        <template #label>
                          <div class="d-flex align-center">
                            <v-icon small color="error" class="mr-1">mdi-close-circle</v-icon>
                            <span class="text-caption">No</span>
                          </div>
                        </template>
                      </v-radio>
                    </v-radio-group>
                  </div>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
        </v-card-text>

        <v-card-actions class="filter-dialog-actions">
          <v-spacer></v-spacer>
          <v-btn
            color="primary"
            @click="showFilterDialog = false"
          >
            Close
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Data Table -->
    <v-data-table
      :headers="headers"
      :items="filteredDiscrepancies"
      :search="search"
      :loading="loading"
      :items-per-page="10"
      class="elevation-1"
    >
      <template #[`item.text`]="{ item }">
        <div class="text-truncate" style="max-width: 300px;">
          {{ item.text }}
        </div>
      </template>

      <template #[`item.labels`]="{ item }">
        <v-simple-table dense class="dataset-table">
          <template #default>
            <thead>
              <tr>
                <th class="dataset-header">Dataset Label</th>
                <th class="dataset-header">Percentage</th>
                <th class="dataset-header">Status</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(percentage, label) in sortedPercentages(item.percentages)" 
                  :key="label" class="dataset-row">
                <td class="dataset-cell">{{ label }}</td>
                <td class="dataset-cell">{{ percentage.toFixed(2) }}%</td>
                <td class="dataset-cell">
                  <v-chip
                    :color="getStatus(item, label, percentage) ===
                     'Agreement' ? 'success' : 'error'"
                    small
                    class="status-chip"
                    style="cursor: pointer;"
                    @click="onStatusClick(item, label, percentage)"
                  >
                    {{ getStatus(item, label, percentage) }}
                  </v-chip>
                </td>
              </tr>
            </tbody>
          </template>
        </v-simple-table>
      </template>

      <template #[`item.is_discrepancy`]="{ item }">
        <v-chip
          :color="overallStatus(item) === 'Agreement' ? 'success' : 'error'"
          small
          class="status-chip"
        >
          {{ overallStatus(item) }}
        </v-chip>
      </template>

      <template #[`item.max_percentage`]="{ item }">
        <span class="percentage-value">{{ item.max_percentage.toFixed(2) }}%</span>
      </template>

      <!-- Novo botão Discussão -->
      <template #[`item.actions`]="{ item }">
        <v-btn small color="primary" @click="goToDiscussion(item)">
          Discussion
        </v-btn>
      </template>
    </v-data-table>

    <!-- Diálogo de Confirmação -->
    <v-dialog v-model="showStatusDialog" max-width="400px">
      <v-card>
        <v-card-title class="headline">
          Confirm State Change
        </v-card-title>
        <v-card-text>
          Deseja alterar o status da discrepância?
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="primary" text @click="confirmChangeStatus">Sim</v-btn>
          <v-btn color="secondary" text @click="showStatusDialog = false">Não</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Snackbars -->
    <v-snackbar v-model="snackbar" timeout="3000" top color="success">
      {{ snackbarMessage }}
      <template #action="{ attrs }">
        <v-btn text v-bind="attrs" @click="snackbar = false">Close</v-btn>
      </template>
    </v-snackbar>

    <v-snackbar v-model="snackbarError" timeout="3000" top color="error">
      {{ snackbarErrorMessage }}
      <template #action="{ attrs }">
        <v-btn text v-bind="attrs" @click="snackbarError = false">Close</v-btn>
      </template>
    </v-snackbar>
  </v-card>
</template>

<script>
import { usePerspectiveApplicationService } from '@/services/application/perspective/perspectiveApplicationService'

export default {
  layout: 'project',
  middleware: ['check-auth', 'auth', 'setCurrentProject'],

  data() {
    return {
      discrepancies: [],
      dbDiscrepancies: [], // nova propriedade para armazenar os dados da BD
      perspectiveGroups: [],
      selectedAnswers: {},
      showFilterDialog: false,
      snackbar: false,
      snackbarMessage: '',
      snackbarError: false,
      snackbarErrorMessage: '',
      loading: true,
      sortOrder: 'desc',
      search: '',
      thresholdPercentage: 70,
      headers: [
        { text: 'Text', value: 'text', sortable: true },
        { text: 'Dataset Labels', value: 'labels', sortable: false },
        { text: 'Overall Status', value: 'is_discrepancy', sortable: true },
        { text: 'Max Percentage', value: 'max_percentage', sortable: true },
        { text: 'Discussão', value: 'actions', sortable: false }
      ],
      showStatusDialog: false,
      selectedDiscrepancy: null,
      selectedDatasetLabel: '',
      selectedPercentage: null,
      autoGenerate: false // nova propriedade para controle de geração automática
    };
  },

  computed: {
    projectId() {
      return this.$route.params.id;
    },
    sortedDiscrepancies() {
      return [...this.discrepancies].sort((a, b) => {
        return this.sortOrder === 'asc' ? a.percentage - b.percentage : 
        b.percentage - a.percentage;
      });
    },
    filteredDiscrepancies() {
      let filtered = [...this.discrepancies];

      const hasPerspectiveFilters = Object.keys(this.selectedAnswers).length > 0;
      console.log('Has perspective filters:', hasPerspectiveFilters);
      console.log('Selected answers:', this.selectedAnswers);

      if (hasPerspectiveFilters) {
        filtered = filtered.filter(discrepancy => {
          const perspectiveAnswers = discrepancy.perspective_answers || {};
          const annotators = discrepancy.annotators || [];
          
          console.log('Processing discrepancy:', discrepancy.text);
          console.log('Perspective answers:', perspectiveAnswers);
          console.log('Annotators:', annotators);

          for (const [selectedQuestionId, selectedValue] of Object.entries(this.selectedAnswers)) {
            if (
              selectedValue === null ||
              selectedValue === undefined ||
              (Array.isArray(selectedValue) && selectedValue.length === 0)
            ) continue;

            console.log(`Checking question ${selectedQuestionId} with value:`, selectedValue);
            console.log(`Selected question ID type:`, typeof selectedQuestionId);
            let matchFound = false;

            for (const group of Object.values(perspectiveAnswers)) {
              for (const [questionId, answersByAnnotator] of Object.entries(group)) {
                console.log(`Comparing question ID: "${selectedQuestionId}" (${typeof selectedQuestionId}) with "${questionId}" (${typeof questionId})`);
                if (questionId !== selectedQuestionId && 
                questionId !== selectedQuestionId.toString()) continue;

                console.log(`Found matching question ${questionId} in group:`, answersByAnnotator);

                for (const annotatorId of annotators) {
                  const rawAnswer = answersByAnnotator[annotatorId];

                  if (rawAnswer !== undefined) {
                    console.log(`Annotator ${annotatorId} answered:`, rawAnswer);
                    
                    if (Array.isArray(selectedValue)) {
                      if (selectedValue.includes(rawAnswer)) {
                        console.log(`Match found for array value: ${rawAnswer} in ${selectedValue}`);
                        matchFound = true;
                        break;
                      }
                    } else if (!isNaN(Number(selectedValue))) {
                      // Para questões do tipo int (valores numéricos)
                      const numericAnswer = Number(rawAnswer);
                      const numericSelected = Number(selectedValue);
                      if (
                        String(selectedValue).trim() !== '' &&
                        !isNaN(numericAnswer) &&
                        !isNaN(numericSelected) &&
                        numericAnswer === numericSelected
                      ) {
                        console.log(`Match found for numeric value: ${numericAnswer} === ${numericSelected}`);
                        matchFound = true;
                        break;
                      }
                    } else {
                      // booleano (corrigido!)
                      const answerStr = rawAnswer.toLowerCase?.();
                      const answerBool =
                        answerStr === 'true' || answerStr === 'yes'
                          ? true
                          : answerStr === 'false' || answerStr === 'no'
                          ? false
                          : null;

                      if (answerBool === null) continue;

                      if (selectedValue === answerBool) {
                        console.log(`Match found for boolean value: ${answerBool} === ${selectedValue}`);
                        matchFound = true;
                        break;
                      }
                    }
                  }
                }
                if (matchFound) break;
              }
              if (matchFound) break;
            }

            if (!matchFound) {
              console.log(`No match found for question ${selectedQuestionId}, filtering out discrepancy`);
              return false;
            }
          }

          console.log(`Discrepancy ${discrepancy.text} passed all filters`);
          return true;
        });
      }

      if (this.sortOrder) {
        filtered.sort((a, b) =>
          this.sortOrder === 'asc'
            ? a.max_percentage - b.max_percentage
            : b.max_percentage - a.max_percentage
        );
      }

      console.log('Final filtered results:', filtered.length);
      return filtered;
    },
    hasActiveFilters() {
      return Object.values(this.selectedAnswers).some(values => {
        if (Array.isArray(values)) {
          return values.length > 0
        }
        return values !== null && values !== undefined
      })
    },
    activeFiltersCount() {
      return Object.values(this.selectedAnswers).reduce((count, values) => {
        if (Array.isArray(values)) {
          return count + values.length;
        }
        return count + (values !== null && values !== undefined ? 1 : 0);
      }, 0);
    }
  },

  watch: {
    selectedAnswers: {
      handler(newVal) {
        localStorage.setItem(`perspectiveFilters-${this.projectId}`, JSON.stringify(newVal));
      },
      deep: true
    }
  },

  async created() {
    this.loadSelectedAnswers();
    await this.fetchDiscrepancies();
    await this.fetchPerspectiveGroups();
  },

  methods: {
    loadSelectedAnswers() {
      const savedFilters = localStorage.getItem(`perspectiveFilters-${this.projectId}`);
      if (savedFilters) {
        try {
          this.selectedAnswers = JSON.parse(savedFilters);
        } catch (e) {
          console.error("Error parsing saved perspective filters:", e);
          this.selectedAnswers = {};
        }
      }
    },
    async fetchDiscrepancies() {
      try {
        const response = await this.$services.discrepancy.listDiscrepancie(this.projectId);
        const dbResponse = await this.$services.discrepancy.getDiscrepanciesDB(this.projectId);
        console.log('Discrepancies from DB:', dbResponse);
        console.log('Discrepancies fetched:', response);
        this.discrepancies = response.discrepancies || [];
        
        // Log da estrutura de uma discrepância para debug
        if (this.discrepancies.length > 0) {
          console.log('Sample discrepancy structure:', this.discrepancies[0]);
        }
        
        // Armazena os dados da BD para uso posterior
        this.dbDiscrepancies = dbResponse || [];
        
        // Atualiza o max_percentage usando todas as percentagens das labels
        this.discrepancies.forEach(item => {
          const percentages = Object.values(item.percentages).map(p => Number(p) || 0);
          item.max_percentage = percentages.length > 0 ? Math.max(...percentages) : 0;
        });

        console.log('autoGenerate:', this.autoGenerate);
        if (this.autoGenerate) {
          this.checkingdbStatus();
        }
        
        // Posta discrepâncias que ainda não existem na BD:
        await this.postDiscrepancie(this.dbDiscrepancies);
      } catch (err) {
        console.error('Error fetching discrepancies:', err);
        if (!err.response || (err.response.status && err.response.status >= 500)) {
          this.snackbarErrorMessage = 'Database unavailable at the moment, please try again later.';
        } else {
          this.snackbarErrorMessage = 'Failed to fetch discrepancies. Please try again later.';
        }
        this.snackbarError = true;
      } finally {
        this.loading = false;
      }
    },

    async checkingdbStatus(){
      console.log('Iniciando verificação de status no DB...');
            const updatePromises = [];
            this.discrepancies.forEach(item => {
                Object.keys(item.percentages).forEach(label => {
                    const percen = item.percentages[label];
                    const statusValue = percen >= this.thresholdPercentage ? 'Agreement' : 'Disagreement';
                    console.log(`Verificando discrepância para '${label}' com percentual ${percen} => status calculado: ${statusValue}`);
                    const dbEntry = this.dbDiscrepancies.find(d =>
                        d.question.trim().toLowerCase() === label.trim().toLowerCase()
                    );
                    if (dbEntry) {
                        console.log(`Status no DB para '${label}': ${dbEntry.status}`);
                        if (dbEntry.status !== statusValue) {
                            console.log(`Atualizando status para '${statusValue}' na discrepância da questão '${label}' (DB estava: ${dbEntry.status})`);
                            updatePromises.push(
                                this.$services.discrepancy.updateDiscrepancyStatus(
                                  this.projectId, label, statusValue)
                            );
                        }
                    } else {
                        console.log(`Não há entrada no DB para a questão '${label}'.`);
                    }
                });
            });
            if (updatePromises.length > 0) {
                console.log(`Serão atualizadas ${updatePromises.length} discrepâncias.`);
                await Promise.all(updatePromises);
                console.log('Atualização de status concluída.');
            } else {
                console.log('Nenhuma discrepância necessitou de atualização.');
            }
            this.autoGenerate = false; // Reseta o flag após a verificação
            this.refreshTable(); // Atualiza a tabela após a verificação
    },

    async postDiscrepancie(dbDiscrepancies) {
      try {
        console.log('Posting discrepancies individually:', this.discrepancies);
        for (const item of this.discrepancies) {
          const labels = Object.keys(item.percentages);
          for (const label of labels) {
            const exists = dbDiscrepancies.some(
              (d) => d.question === label
            );
            if (exists) {
              console.log(`Discrepancy for label ${label} already exists, skipping.`);
              continue;
            }
            const percen = item.percentages[label];
            const statusValue = percen >= this.thresholdPercentage
              ? 'Agreement'
              : 'Disagreement';
            const payload = {
              question: label,
              status: statusValue,
              created_at: new Date().toISOString(),
              projectId: this.projectId,
              percentage: percen,
            };
            console.log('Posting discrepancy for label:', payload);
            const response = await this.$services.discrepancy.postDiscrepancies(
              this.projectId, payload
            );
            console.log('Discrepancy posted:', response);
          }
        }
      } catch (err) {
        console.error('Error posting discrepancies:', err);
        if (!err.response || (err.response.status && err.response.status >= 500)) {
          this.snackbarErrorMessage = 'Database unavailable at the moment, please try again later.';
        } else {
          this.snackbarErrorMessage = 'Failed to post discrepancies. Please try again later.';
        }
        this.snackbarError = true;
      }
    },

    async fetchPerspectiveGroups() {
      try {
        const service = usePerspectiveApplicationService();
        const response = await service.listPerspectiveGroups(this.projectId);
        this.perspectiveGroups = response.results || [];
      } catch (err) {
        console.error('Error fetching perspective groups:', err);
        if (!err.response || (err.response.status && err.response.status >= 500)) {
          this.snackbarErrorMessage = 'Database unavailable at the moment, please try again later.';
        } else {
          this.snackbarErrorMessage = 'Failed to fetch perspective groups.';
        }
        this.snackbarError = true;
      }
    },

    applyFilters() {
      console.log('Applying filters...');
      console.log('Selected answers:', this.selectedAnswers);
      console.log('Discrepancies:', this.discrepancies);
    },

    updateSort() {
      // ...lógica de ordenação se necessário...
    },

    sortedPercentages(percentages) {
      const sorted = Object.entries(percentages).sort((a, b) => {
        return this.sortOrder === 'asc' ? a[1] - b[1] : b[1] - a[1];
      });
      return Object.fromEntries(sorted);
    },

    clearFilters() {
      console.log('Clearing filters...');
      this.selectedAnswers = {};
      this.$nextTick(() => {
        this.applyFilters();
      });
    },

    goToDiscussion(item) {
      this.$router.push(this.localePath(`/projects/${this.projectId}/discrepancies/${item.id}`));
    },

    onStatusClick(discrepancy, label, percentage) {
      this.selectedDiscrepancy = discrepancy;
      this.selectedDatasetLabel = label;
      this.selectedPercentage = percentage;
      this.showStatusDialog = true;
      console.log("Clicou no status da discrepância:", discrepancy, "para o dataset:", label);
    },

    async confirmChangeStatus() {
      if (this.selectedDiscrepancy && this.selectedDatasetLabel) {
        // Altera o status localmente (alternando entre Agreement e Disagreement)
        const currentStatus = this.getStatus(
          this.selectedDiscrepancy,
          this.selectedDatasetLabel,
          this.selectedPercentage
        );
        const newStatus = currentStatus === 'Agreement' ? 'Disagreement' : 'Agreement';
        if (!this.selectedDiscrepancy.statusOverrides) {
          this.$set(this.selectedDiscrepancy, 'statusOverrides', {});
        }
        this.$set(this.selectedDiscrepancy.statusOverrides, this.selectedDatasetLabel, newStatus);

        // Chama o endpoint com PATCH – apenas uma requisição para alterar o status
        await this.$services.discrepancy.updateDiscrepancyStatus(
          this.projectId,
          this.selectedDatasetLabel
        );

        await this.refreshTable();

        // Recalcula o max_percentage com base nas percentagens do próprio item
        const percentages = 
        Object.values(this.selectedDiscrepancy.percentages).map(p => Number(p) || 0);
        this.selectedDiscrepancy.max_percentage = 
        percentages.length > 0 ? Math.max(...percentages) : 0;

        this.snackbarMessage = 'Status atualizado e max percentage recalculado';
        this.snackbar = true;
      }
      this.showStatusDialog = false;
    },

    // Método getStatus que buscará o status na lista dbDiscrepancies
    getStatus(item, label, percentage) {
      console.log('item', Object.keys(item));
      const dbEntry = this.dbDiscrepancies.find(d => d.question === label);
      if (dbEntry) {
        return dbEntry.status;
      }
      return percentage >= this.thresholdPercentage ? 'Agreement' : 'Disagreement';
    },

    overallStatus(item) {
      return item.max_percentage >= this.thresholdPercentage
        ? 'Agreement'
        : 'Disagreement';
    },

    autoGenerateDiscrepancies() {
      console.log('Auto-generating discrepancies...');
      this.autoGenerate = true;
      this.refreshTable();
    },

    refreshTable() {
      this.loading = true;
      Promise.all([
        this.fetchDiscrepancies(),
        this.fetchPerspectiveGroups()
      ])
        .then(() => {
          this.snackbarMessage = 'Discrepâncias Geradas Automaticamente';
          this.snackbar = true;
        })
        .catch((err) => {
          console.error('Erro ao atualizar tabela:', err);
          this.snackbarErrorMessage = 'Erro ao atualizar tabela';
          this.snackbarError = true;
        })
    }
  }
};
</script>

<style scoped>
.v-data-table {
  width: 100%;
}

.dataset-table {
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  margin: 8px 0;
  box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

.dataset-header {
  background-color: #f5f5f5 !important;
  font-weight: 600 !important;
  color: #424242 !important;
  padding: 8px 16px !important;
  border-bottom: 2px solid #e0e0e0 !important;
}

.dataset-row {
  border-bottom: 1px solid #e0e0e0;
}

.dataset-row:last-child {
  border-bottom: none;
}

.dataset-cell {
  padding: 12px 16px !important;
  font-size: 0.9rem;
}

.status-chip {
  font-weight: 500;
  min-width: 100px;
  justify-content: center;
}

.percentage-value {
  font-weight: 600;
  color: #424242;
}

/* Estilo para o texto truncado */
.text-truncate {
  max-width: 300px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  line-height: 1.4;
}

/* Estilo para a tabela principal */
.v-data-table ::v-deep th {
  font-weight: 600 !important;
  color: #424242 !important;
  background-color: #f5f5f5 !important;
}

.v-data-table ::v-deep td {
  padding: 16px !important;
}

/* Estilo para as linhas alternadas */
.v-data-table ::v-deep tbody tr:nth-of-type(odd) {
  background-color: #fafafa;
}

/* Estilo para hover nas linhas */
.v-data-table ::v-deep tbody tr:hover {
  background-color: #f5f5f5;
}

.filter-btn {
  background: linear-gradient(145deg, #e3f2fd, #bbdefb) !important;
  color: #1976d2 !important;
  border-radius: 24px;
  padding: 0 24px;
  height: 40px;
  font-weight: 500;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
  display: flex;
  justify-content: center;
  align-items: center;
}

.filter-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.filter-dialog-card {
  border-radius: 16px;
  overflow: hidden;
}

.filter-dialog-title {
  background: linear-gradient(145deg, #e3f2fd, #bbdefb);
  padding: 16px 24px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
}

.filter-dialog-content {
  padding: 24px;
  max-height: 70vh;
  overflow-y: auto;
}

.filter-dialog-actions {
  padding: 16px 24px;
  background: #f5f5f5;
  border-top: 1px solid rgba(0, 0, 0, 0.05);
}

.perspective-filter-card {
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 12px;
  transition: all 0.3s ease;
  background: linear-gradient(145deg, #ffffff, #fafafa);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.03);
  margin-bottom: 16px;
}

.perspective-filter-card:hover {
  box-shadow: 0 8px 16px rgba(0, 0, 0, 0.08);
  transform: translateY(-2px);
}

.perspective-filter-card .v-card-title {
  background: linear-gradient(145deg, #e8f5e9, #c8e6c9);
  border-radius: 12px 12px 0 0;
  padding: 12px 16px;
}

.perspective-filter-card .v-card-title .v-icon {
  color: #2e7d32;
}

.perspective-filter-card .v-card-text {
  padding: 16px;
}

.v-select ::v-deep .v-select__selections {
  flex-wrap: nowrap;
}

.v-select ::v-deep .v-chip {
  margin: 2px;
  background: linear-gradient(145deg, #e3f2fd, #bbdefb) !important;
  border: none !important;
}

.v-radio ::v-deep .v-radio__label {
  font-size: 0.9rem;
  color: rgba(0, 0, 0, 0.87);
}

.clear-filters-btn {
  background: linear-gradient(145deg, #ffebee, #ffcdd2) !important;
  color: #c62828 !important;
  border-radius: 16px;
  padding: 0 16px;
  height: 32px;
  font-weight: 500;
}

.clear-filters-btn:hover {
  background: linear-gradient(145deg, #ffcdd2, #ef9a9a) !important;
  transform: translateY(-1px);
}

/* Add styles for the filter groups */
.perspective-filter-card .text-subtitle-1 {
  color: #1b5e20;
  font-weight: 600;
}

.perspective-filter-card .text-subtitle-2 {
  color: #2e7d32;
  font-weight: 500;
}

/* Style for the select and radio inputs */
.v-select ::v-deep .v-input__slot {
  background: rgba(255, 255, 255, 0.8);
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.02);
}

.v-radio-group ::v-deep .v-radio {
  margin-right: 24px;
}

.v-radio-group ::v-deep .v-radio__label {
  color: #424242;
}

/* Custom scrollbar for the dialog content */
.filter-dialog-content::-webkit-scrollbar {
  width: 8px;
}

.filter-dialog-content::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 4px;
}

.filter-dialog-content::-webkit-scrollbar-thumb {
  background: #bbdefb;
  border-radius: 4px;
}

.filter-dialog-content::-webkit-scrollbar-thumb:hover {
  background: #90caf9;
}
</style>